config/routes.rb
Rails.application.routes.draw do

  resources :parties

  get 'calendar/show'

  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"


end

app/models/party.rb
class Party < ActiveRecord::Base
  validates :who,:what,:where,:when,:phone, presence: true;
  validate :cannot_party_in_the_past, on: :create;
  validates :phone, length: {minimum: 10, message: "number needed" }

  def cannot_party_in_the_past
    if self.when.present? && self.when < Date.today
      errors.add(:when, "can't be in the past")
    end
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = Party.all.group_by do |party|
      Date.parse(party.when.to_s)
    end
  end
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
    if (date = params[:date]).present?
      @party.when = params[:date]
    end
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:when, :who, :what, :where, :phone, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">

    <%= calendar @date do |date| %>
          <%= date.day %>
      <% if @events_by_date[date] %>
        <ul>
          <% @events_by_date[date].each do |event| %>
            <% if event.when.hour == 0 %>
            <span><li><%= link_to "#{event.who}", event %></li></span>
            <% else %>
            <span><li><%= link_to "#{event.who} at #{event.when.hour}:#{event.when.min}", event %></li></span>
            <% end %>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booking Calendar</title>
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <% if @party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
      <% @party.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :when %><br>
    <%= f.datetime_select :when %>
  </div>
  <div class="field">
    <%= f.label :who, "Who is throwing this party?" %><br>
    <%= f.text_field :who %>
  </div>
  <div class="field">
    <%= f.label :what, "What type of party will this be?" %><br>
    <%# f.text_field :what %>
    <%= f.select :what, ['Pool Party', 'Movie Nights','F@#$!& RAGER','DJ Services']%>
  </div>
  <div class="field">
    <%= f.label :where, "Where is this party going to be hosted?"%><br>
    <%= f.text_field :where %>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone number*" %><br>
    <%= f.text_field :phone %>
  </div>
  <!-- <div class="field">
    <%# f.label :cost,  %><br>
    <%# f.text_field :cost %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
    <!-- <script>alert('No users!')</script> -->
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parties</h1>

<table>
  <thead>
    <tr>
      <th>When</th>
      <th>Who</th>
      <th>What</th>
      <th>Where</th>
      <th>Phone</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parties.each do |party| %>
      <tr>
        <td><%= party.when %></td>
        <td><%= party.who %></td>
        <td><%= party.what %></td>
        <td><%= party.where %></td>
        <td><%= party.phone %></td>
        <td><%= party.cost %></td>
        <td><%= link_to 'Show', party %></td>
        <td><%= link_to 'Edit', edit_party_path(party) %></td>
        <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>Book the best DJs in town</h1>

<h3>So you've made the smart decision to have Funxtable help you throw your party, <br>
  but first we need some info from you: <br><br></h3>
<%= render 'form' %>


<%= link_to 'Back', calendar_path %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>When:</strong>
  <%= @party.when %>
</p>

<p>
  <strong>Who:</strong>
  <%= @party.who %>
</p>

<p>
  <strong>What:</strong>
  <%= @party.what %>
</p>

<p>
  <strong>Where:</strong>
  <%= @party.where %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @party.phone %>
</p>

<!-- <p>
  <strong>Cost:</strong>
  <%= @party.cost %>
</p> -->

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', calendar_path %>

<script>alert('Thank you! We will be contacting you within the next 24 hours to confirm your booking!')</script>